export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const GET_LOGIN_DETAILS = "GET_LOGIN_DETAILS";
export const FETCH_USER_DETAILS_ERROR = "FETCH_USER_DETAILS_ERROR";
export const FETCH_USER_LOGIN_ERROR = "FETCH_USER_LOGIN_ERROR";
export const FETCH_USER_TOKEN = "FETCH_USER_TOKEN";
